# Generated by Django 2.0.3 on 2018-05-23 22:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bloodtype',
            field=models.CharField(blank=True, choices=[('0-', 'O negative'), ('A-', 'A negative'), ('B-', 'B negative'), ('AB-', 'AB negative'), ('0+', 'O positive'), ('A+', 'A positive'), ('B+', 'B positive'), ('AB+', 'AB positive')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Age of User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email of User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ManyToManyField(blank=True, null=True, to='bloodmanager.Institution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodmanager.Location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone number of User'),
        ),
    ]
