# Generated by Django 2.0.3 on 2018-05-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180524_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ManyToManyField(blank=True, to='bloodmanager.Institution'),
        ),
    ]
