# Generated by Django 2.0.3 on 2018-05-23 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloodmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount of blood')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bloodmanager.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(verbose_name='Date and time of expiration date')),
                ('bloodtype', models.CharField(choices=[('0-', 'O negative'), ('A-', 'A negative'), ('B-', 'B negative'), ('AB-', 'AB negative'), ('0+', 'O positive'), ('A+', 'A positive'), ('B+', 'B positive'), ('AB+', 'AB positive')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Date and time of Donation')),
                ('report', models.NullBooleanField(default=False, verbose_name='Blood donation report')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bloodmanager.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bloodmanager.Donation'),
        ),
    ]
