# Generated by Django 2.0.3 on 2018-05-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodmanager', '0002_auto_20180524_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodamount',
            name='bloodtype',
            field=models.CharField(choices=[('0-', 'O negative'), ('A-', 'A negative'), ('B-', 'B negative'), ('AB-', 'AB negative'), ('0+', 'O positive'), ('A+', 'A positive'), ('B+', 'B positive'), ('AB+', 'AB positive')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
