# Generated by Django 2.0.3 on 2018-05-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodmanager', '0005_event_eventuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bloodmanager.Event'),
            preserve_default=False,
        ),
    ]
